### ISSUE TITLE
ToDo for November

### ISSUE THREAD

**Issue by josefpolasek** [josefpolasek/profile#1]
- [ ] remove Bootstrap (after grading)
- [ ] make the website dynamic (compatible for phones)
- [ ] update 'My Projects' part 
  - [ ] new design of projects cards
  - [ ] overview of projects
  - [ ] add projects
    - [ ] ToDo App
    - [x] #2
    - [ ] Quiz
    - [ ] Login page
    - [ ] simple drawing app
    - [ ] photographer's page
    - [ ] Ask Yoda
- [ ] update 'Skills' part (tags for projects)
- [ ] add a link to blog/page with photos
- [ ] add 3 CSS animation (special effets)
